[package]
name = "llcli_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
config = { version = "0.15.11" }
reqwest = { version = "0.12.15" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
dirs = { version = "6.0.0" }
